"""restructure_calls_recordings

Revision ID: 4e74f1a41b27
Revises: 047f11b270d8
Create Date: 2026-05-05 21:52:33.306781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e74f1a41b27'
down_revision: Union[str, Sequence[str], None] = '047f11b270d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('call_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_type_id'], ['call_types.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_business_id'), 'calls', ['business_id'], unique=False)
    op.create_index(op.f('ix_calls_client_id'), 'calls', ['client_id'], unique=False)
    op.create_table('call_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_summaries_business_id'), 'call_summaries', ['business_id'], unique=False)
    op.create_index(op.f('ix_call_summaries_call_id'), 'call_summaries', ['call_id'], unique=True)
    op.create_table('next_action_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_action_steps_business_id'), 'next_action_steps', ['business_id'], unique=False)
    op.create_index(op.f('ix_next_action_steps_call_id'), 'next_action_steps', ['call_id'], unique=False)
    op.drop_table('extractions')
    op.add_column('queries', sa.Column('call_id', sa.Uuid(), nullable=False))
    op.add_column('queries', sa.Column('business_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_queries_business_id'), 'queries', ['business_id'], unique=False)
    op.create_index(op.f('ix_queries_call_id'), 'queries', ['call_id'], unique=False)
    op.drop_constraint(op.f('queries_recording_id_fkey'), 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'calls', ['call_id'], ['id'])
    op.create_foreign_key(None, 'queries', 'businesses', ['business_id'], ['id'])
    op.drop_column('queries', 'recording_id')
    op.add_column('recordings', sa.Column('call_id', sa.Uuid(), nullable=False))
    op.add_column('recordings', sa.Column('s3_key', sa.String(length=1000), nullable=True))
    op.drop_index(op.f('ix_recordings_client_id'), table_name='recordings')
    op.create_index(op.f('ix_recordings_call_id'), 'recordings', ['call_id'], unique=True)
    op.drop_constraint(op.f('recordings_created_by_id_fkey'), 'recordings', type_='foreignkey')
    op.drop_constraint(op.f('recordings_client_id_fkey'), 'recordings', type_='foreignkey')
    op.drop_constraint(op.f('recordings_call_type_id_fkey'), 'recordings', type_='foreignkey')
    op.create_foreign_key(None, 'recordings', 'calls', ['call_id'], ['id'])
    op.drop_column('recordings', 'client_name')
    op.drop_column('recordings', 'title')
    op.drop_column('recordings', 'status')
    op.drop_column('recordings', 'recorded_at')
    op.drop_column('recordings', 'duration_seconds')
    op.drop_column('recordings', 'client_id')
    op.drop_column('recordings', 'call_type_id')
    op.drop_column('recordings', 'file_path')
    op.drop_column('recordings', 'created_by_id')
    op.add_column('transcripts', sa.Column('call_id', sa.Uuid(), nullable=False))
    op.add_column('transcripts', sa.Column('business_id', sa.Uuid(), nullable=False))
    op.add_column('transcripts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('transcripts_recording_id_key'), 'transcripts', type_='unique')
    op.create_index(op.f('ix_transcripts_business_id'), 'transcripts', ['business_id'], unique=False)
    op.create_index(op.f('ix_transcripts_call_id'), 'transcripts', ['call_id'], unique=True)
    op.drop_constraint(op.f('transcripts_recording_id_fkey'), 'transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'transcripts', 'calls', ['call_id'], ['id'])
    op.create_foreign_key(None, 'transcripts', 'businesses', ['business_id'], ['id'])
    op.drop_column('transcripts', 'recording_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('recording_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_foreign_key(op.f('transcripts_recording_id_fkey'), 'transcripts', 'recordings', ['recording_id'], ['id'])
    op.drop_index(op.f('ix_transcripts_call_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_business_id'), table_name='transcripts')
    op.create_unique_constraint(op.f('transcripts_recording_id_key'), 'transcripts', ['recording_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('transcripts', 'updated_at')
    op.drop_column('transcripts', 'business_id')
    op.drop_column('transcripts', 'call_id')
    op.add_column('recordings', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('call_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recordings', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('recordings', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.create_foreign_key(op.f('recordings_call_type_id_fkey'), 'recordings', 'call_types', ['call_type_id'], ['id'])
    op.create_foreign_key(op.f('recordings_client_id_fkey'), 'recordings', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('recordings_created_by_id_fkey'), 'recordings', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_recordings_call_id'), table_name='recordings')
    op.create_index(op.f('ix_recordings_client_id'), 'recordings', ['client_id'], unique=False)
    op.drop_column('recordings', 's3_key')
    op.drop_column('recordings', 'call_id')
    op.add_column('queries', sa.Column('recording_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key(op.f('queries_recording_id_fkey'), 'queries', 'recordings', ['recording_id'], ['id'])
    op.drop_index(op.f('ix_queries_call_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_business_id'), table_name='queries')
    op.drop_column('queries', 'business_id')
    op.drop_column('queries', 'call_id')
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recording_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_used', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('call_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_type_id'], ['call_types.id'], name=op.f('extractions_call_type_id_fkey')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('extractions_recording_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extractions_pkey'))
    )
    op.drop_index(op.f('ix_next_action_steps_call_id'), table_name='next_action_steps')
    op.drop_index(op.f('ix_next_action_steps_business_id'), table_name='next_action_steps')
    op.drop_table('next_action_steps')
    op.drop_index(op.f('ix_call_summaries_call_id'), table_name='call_summaries')
    op.drop_index(op.f('ix_call_summaries_business_id'), table_name='call_summaries')
    op.drop_table('call_summaries')
    op.drop_index(op.f('ix_calls_client_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_business_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
